### ISSUE TITLE
Stuck on sending Message

### ISSUE THREAD

**Issue by DRAMA22** [mmdzov/poe-chat-api#1]
```
(async () => {
    const instance = new Client(process.env.TOKEN, {
      showSteps: true,
    });
  
    const client = await instance.init();
  
    await client.sendMessage(
      {
        message: "Hello world",
      },
      (response) => {
        console.log(response);
      },
    );
  })();
```

output

Downloading Settings...
Waiting for Clients
Downloading next_data...
Subscribing...
WebSocket Connecting...
WebSocket connected!
Sending message...

**Comment by netneurons** [comment]
Me too brother. I am using Glitch and you?

**Comment by cctv1005s** [comment]
My PR resolved this: https://github.com/mmdzov/poe-chat-api/pull/2/files

**Comment by mmdzov** [comment]
The [changes](https://github.com/mmdzov/poe-chat-api/pull/2) were merged
